const peopleChoiceData = [
  {
    username: "aditeyaS",
    favAnime: "One Piece",
    favAnimeID: "37854",
    favMovie: "14 Peaks: Nothing Is Impossible",
    favMovieID: "890825-14-peaks-nothing-is-impossible",
    favSeries: "Mr. Robot",
    favSeriesID: "62560-mr-robot",
  },
  {
    username: "tanishqj-19",
    favAnime: "Jujutsu Kaisen",
    favAnimeID: "95479",
    favMovie: "Fight Club",
    favMovieID: "550-fight-club",
    favSeries: "Breaking Bad",
    favSeriesID: "1396-breaking-bad",
  },
  {
    username: "icepick4",
    favAnime: "One Piece",
    favAnimeID: "37854",
    favMovie: "Back to the Future",
    favMovieID: "105-back-to-the-future",
    favSeries: "Breaking Bad",
    favSeriesID: "1396-breaking-bad",
  },
  {
    username: "sumant7",
    favAnime: "Attack on Titan",
    favAnimeID: "1429",
    favMovie: "Blade Runner 2049",
    favMovieID: "335984-blade-runner-2049",
    favSeries: "Peaky Blinders",
    favSeriesID: "60574-peaky-blinders",
  },
  {
    username: "sejal-bansal",
    favAnime: "SPY x FAMILY",
    favAnimeID: "120089",
    favMovie: "Black Panther",
    favMovieID: "284054-black-panther",
    favSeries: "Big Bang Theory",
    favSeriesID: "1418-the-big-bang-theory",
  },
  {
    username: "arjunpndt",
    favAnime: "One Piece",
    favAnimeID: "37854",
    favMovie: "Perfect Blue",
    favMovieID: "10494-perfect-blue",
    favSeries: "peaky blinders",
    favSeriesID: "60574-peaky-blinders",
  },
  {
    username: "GettingWeirdKnowledge",
    favAnime: "Gintama",
    favAnimeID: "57041-gin-tama",
    favMovie: "The Shawshank redemption",
    favMovieID: "278-the-shawshank-redemption",
    favSeries: "The big bang theory",
    favSeriesID: "1418-the-big-bang-theory",
  },
  {
    username: "Maheshwar-S",
    favAnime: "Kaiji",
    favAnimeID: "42951",
    favMovie: "Coco",
    favMovieID: "354912-coco",
    favSeries: "Breaking Bad",
    favSeriesID: "1396-breaking-bad",
  },
  {
    username: "guilhermeorcezi",
    favAnime: "March Comes in Like a Lion",
    favAnimeID: "65336",
    favMovie: "Liz and the Blue Bird",
    favMovieID: "482150",
    favSeries: "Breaking Bad",
    favSeriesID: "1396-breaking-bad",
  },
  {
    username: "abrehan2",
    favAnime: "Naruto Shippūden",
    favAnimeID: "31910",
    favMovie: "Ready Player One",
    favMovieID: "333339-ready-player-one",
    favSeries: "Dark",
    favSeriesID: "70523-dark",
  },
  {
    username: "destryptor",
    favAnime: "Violet Evergarden",
    favAnimeID: "75214-violet-evergarden",
    favMovie: "Oppenheimer",
    favMovieID: "872585-oppenheimer",
    favSeries: "Lucifer",
    favSeriesID: "63174-lucifer",
  },
  {
    username: "coder-bat",
    favAnime: "Attack on Titan",
    favAnimeID: "1429",
    favMovie: "The Truman Show",
    favMovieID: "37165-the-truman-show",
    favSeries: "Person of Interest",
    favSeriesID: "1411-person-of-interest",
  },
];
