const peopleChoiceData = [
  {
    username: 'AirOne01',
    favAnime: 'Sword Art Online',
    favAnimeID: '45782',
    favMovie: 'Interstellar',
    favMovieID: '157336',
    favSeries: 'Mr. Robot',
    favSeriesID: '62560'
  },
  {
    username: "aditeyaS",
    favAnime: "One Piece",
    favAnimeID: "37854",
    favMovie: "14 Peaks: Nothing Is Impossible",
    favMovieID: "890825-14-peaks-nothing-is-impossible",
    favSeries: "Mr. Robot",
    favSeriesID: "62560-mr-robot",
  },
  {
    username: "tanishqj-19",
    favAnime: "Jujutsu Kaisen",
    favAnimeID: "95479",
    favMovie: "Fight Club",
    favMovieID: "550-fight-club",
    favSeries: "Breaking Bad",
    favSeriesID: "1396-breaking-bad",
  },
  {
    username: "icepick4",
    favAnime: "One Piece",
    favAnimeID: "37854",
    favMovie: "Back to the Future",
    favMovieID: "105-back-to-the-future",
    favSeries: "Breaking Bad",
    favSeriesID: "1396-breaking-bad",
  },
  {
    username: "sumant7",
    favAnime: "Attack on Titan",
    favAnimeID: "1429",
    favMovie: "Blade Runner 2049",
    favMovieID: "335984-blade-runner-2049",
    favSeries: "Peaky Blinders",
    favSeriesID: "60574-peaky-blinders",
  },
  {
    username: "sejal-bansal",
    favAnime: "SPY x FAMILY",
    favAnimeID: "120089",
    favMovie: "Black Panther",
    favMovieID: "284054-black-panther",
    favSeries: "The Big Bang Theory",
    favSeriesID: "1418-the-big-bang-theory",
  },
  {
    username: "arjunpndt",
    favAnime: "One Piece",
    favAnimeID: "37854",
    favMovie: "Perfect Blue",
    favMovieID: "10494-perfect-blue",
    favSeries: "peaky blinders",
    favSeriesID: "60574-peaky-blinders",
  },
  {
    username: "GettingWeirdKnowledge",
    favAnime: "Gintama",
    favAnimeID: "57041-gin-tama",
    favMovie: "The Shawshank Redemption",
    favMovieID: "278-the-shawshank-redemption",
    favSeries: "The big bang theory",
    favSeriesID: "1418-the-big-bang-theory",
  },
  {
    username: "Maheshwar-S",
    favAnime: "Kaiji",
    favAnimeID: "42951",
    favMovie: "Coco",
    favMovieID: "354912-coco",
    favSeries: "Breaking Bad",
    favSeriesID: "1396-breaking-bad",
  },
  {
    username: "guilhermeorcezi",
    favAnime: "March Comes in Like a Lion",
    favAnimeID: "65336",
    favMovie: "Liz and the Blue Bird",
    favMovieID: "482150",
    favSeries: "Breaking Bad",
    favSeriesID: "1396-breaking-bad",
  },
  {
    username: "abrehan2",
    favAnime: "Naruto Shippūden",
    favAnimeID: "31910",
    favMovie: "Ready Player One",
    favMovieID: "333339-ready-player-one",
    favSeries: "Dark",
    favSeriesID: "70523-dark",
  },
  {
    username: "Muanra217",
    favAnime: "Monogatari",
    favAnimeID: "46195",
    favMovie: "Ready Player One",
    favMovieID: "333339-ready-player-one",
    favSeries: "The big bang theory",
    favSeriesID: "1418-the-big-bang-theory",
  },
  {
    username: "destryptor",
    favAnime: "Violet Evergarden",
    favAnimeID: "75214-violet-evergarden",
    favMovie: "Oppenheimer",
    favMovieID: "872585-oppenheimer",
    favSeries: "Lucifer",
    favSeriesID: "63174-lucifer",
  },
  {
    username: "U7K4R5H",
    favAnime: "Death Note",
    favAnimeID: "13916-death-note",
    favMovie: "12 Angry Men",
    favMovieID: "389-12-angry-men",
    favSeries: "Breaking Bad",
    favSeriesID: "1396-breaking-bad",
  },
  {
    username: "coder-bat",
    favAnime: "Attack on Titan",
    favAnimeID: "1429",
    favMovie: "The Truman Show",
    favMovieID: "37165-the-truman-show",
    favSeries: "Person of Interest",
    favSeriesID: "1411-person-of-interest",
  },
  {
    username: "combfreak45",
    favAnime: "Mob Psycho 100",
    favAnimeID: "67075-100",
    favMovie: "The Hangover",
    favMovieID: "18785-the-hangover",
    favSeries: "Dark",
    favSeriesID: "70523-dark",
  },
  {
    username: "pankaj-2503",
    favAnime: "Demon Slayer: Kimetsu no Yaiba",
    favAnimeID: "85937",
    favMovie: "The Maze Runner",
    favMovieID: "198663-the-maze-runner",
    favSeries: "Money Heist",
    favSeriesID: "71446-la-casa-de-papel",
  },
  {
    username: "gauravbhaskar080",
    favAnime: "Naruto Shippuden",
    favAnimeID: "31910",
    favMovie: "Interstellar",
    favMovieID: "157336-interstellar",
    favSeries: "Game of Thrones",
    favSeriesID: "1399-game-of-thrones",
  },
  {
    username: "roxoho",
    favAnime: "Chobits",
    favAnimeID: "37527-chobits",
    favMovie: "I Am Number Four",
    favMovieID: "46529-i-am-number-four",
    favSeries: "Loki",
    favSeriesID: "84958-loki",
  },
  {
    username: "x3shat",
    favAnime: "One Piece",
    favAnimeID: "37854",
    favMovie: "The Shawshank Redemption",
    favMovieID: "278-the-shawshank-redemption",
    favSeries: "Friends",
    favSeriesID: "1668-friends",
  },
  {
    username: "saurabh29r",
    favAnime: "Spirited Away",
    favAnimeID: "1001196",
    favMovie: "The Internship",
    favMovieID: "116741-the-internshipe",
    favSeries: "Mirzapur",
    favSeriesID: "84105-mirzapur",
  },
  {
    username: "divyanshu29jha",
    favAnime: "Bleach",
    favAnimeID: "30984-bleach",
    favMovie: "After Everything",
    favMovieID: "820525-after-everything",
    favSeries: "Suits",
    favSeriesID: "37680-suits",
  },
  {
    username: "nisoojadhav",
    favAnime: "High School of the Dead",
    favAnimeID: "56998-gakuen-mokushiroku-high-school-of-the-dead",
    favMovie: "Good Will Hunting",
    favMovieID: "489-good-will-hunting",
    favSeries: "Squid Game",
    favSeriesID: "93405",
  },
  {
    username: "sandesh-theMayGuy",
    favAnime: "Death Note",
    favAnimeID: "13916-death-note",
    favMovie: "Shutter Island",
    favMovieID: "11324-shutter-island",
    favSeries: "Loki",
    favSeriesID: "84958-loki",
  },
  {
    username: "fahmi-azzuhri",
    favAnime: "That Time I Got Reincarnated as a Slime",
    favAnimeID: "82684",
    favMovie: "Ong-Bak",
    favMovieID: "9316-ong-bak",
    favSeries: null,
    favSeriesID: null,
  },
  {
    username: "BlankAmber",
    favAnime: "Grimgar of Fantasy and Ash",
    favAnimeID: "65369",
    favMovie: "Toy Story",
    favMovieID: "862-toy-story",
    favSeries: "Reset",
    favSeriesID: "155441",
  },
  {
    username: "ankushtripathii",
    favAnime: "Vinland Saga",
    favAnimeID: "88803",
    favMovie: "The Martian",
    favMovieID: "286217-the-martian",
    favSeries: "The Rain",
    favSeriesID: "76719-the-rain",
  },
  {
    username: "izabela-marcinkowska",
    favAnime: "Cells at Work!",
    favAnimeID: "80671",
    favMovie: "Up",
    favMovieID: "14160-up",
    favSeries: "The Office",
    favSeriesID: "2316-the-office",
  },
  {
    username: "Chaitanya Sesha Govind",
    favAnime: "Death Note",
    favAnimeID: "13916-death-note",
    favMovie: "Interstellar",
    favMovieID: "157336-interstellar",
    favSeries: "Game of Thrones",
    favSeriesID: "1399-game-of-thrones",
  },
  {
    username: "vishnuSandeep1108",
    favAnime: "Black Clover",
    favAnimeID: "73223-black-clover",
    favMovie: "Interstellar",
    favMovieID: "157336-interstellar",
    favSeries: "The Mentalist",
    favSeriesID: "5920-the-mentalist",
  },
  {
    username: "hijal",
    favAnime: "Lookism",
    favAnimeID: "210942-lookism",
    favMovie: "Sonic the Hedgehog",
    favMovieID: "454626-sonic-the-hedgehog",
    favSeries: "Game of Thrones",
    favSeriesID: "1399-game-of-thrones",
  },
  {
    username: "PatrickNv23",
    favAnime: "One Piece",
    favAnimeID: "37854",
    favMovie: "Spider-Man",
    favMovieID: "557-spider-man",
    favSeries: "Silicon Valley",
    favSeriesID: "60573-silicon-valley",
  },
  {
    username: "prabhat224",
    favAnime: "Parasyte -the maxim",
    favAnimeID: "61459-kiseij-sei-no-kakuritsu",
    favMovie: "American Psycho",
    favMovieID: "1359-american-psycho",
    favSeries: "Vikings",
    favSeriesID: "44217-vikings",
  },
  {
    username: "imsherlocked",
    favAnime: "Death Note",
    favAnimeID: "13916-death-note",
    favMovie: "The Avengers: End Game",
    favMovieID: "299534-avengers-endgame",
    favSeries: "Friends",
    favSeriesID: "1668-friends",
  },
  {
    username: "Akilan_19",
    favAnime: "Paranoia Agent",
    favAnimeID: "9343-mousou-dairinin",
    favMovie: "Shutter Island",
    favMovieID: "11324-shutter-island",
    favSeries: "Chernobyl",
    favSeriesID: "87108-chernobyl",
  },
  {
    username: "lolomaku",
    favAnime: "Frieren: Beyond Journey's End",
    favAnimeID: "209867",
    favMovie: "Zack Snyder's Justice League",
    favMovieID: "791373-zack-snyder-s-justice-league",
    favSeries: "Sense8",
    favSeriesID: "61664-sense8",
  },
  {
    username: "Akilan19",
    favAnime: "Tsuritama",
    favAnimeID: "45283-tsuritama",
    favMovie: "Sound of Freedom",
    favMovieID: "678512-sound-of-freedom",
    favSeries: "Once",
    favSeriesID: "72637-o11ce",
  },
];
